version: "3"

services:
  db:
    image: mysql
    ports:
    - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: s3
      MYSQL_USER: s3_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    restart: always