spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s3?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: s3_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
cloud:
  aws:
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      bucket: ${bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
